name: build


on:

  schedule:
  - cron: "0 23 */2 * *"
  push:
    branches: [ "master" ]
    paths-ignore:
    - 'org.polymc.PolyMC.yml'
    - '.github/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install flatpak and flatpak-builder
        run: sudo apt install flatpak flatpak-builder -y
        
      - name: add flathub repo
        run: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build flatpak bundle
        run: |
          mkdir build
          sudo flatpak-builder --install-deps-from=flathub build org.polymc.PolyMC-git.yml
          flatpak build-export export build
          flatpak build-bundle export "org.polymc.PolyMC.flatpak" org.polymc.PolyMC --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: org.polymc.PolyMC.flatpak
          path: org.polymc.PolyMC.flatpak

