name: release


on:

  push:
     tags:
     - "*"
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install flatpak and flatpak-builder
        run: sudo apt install flatpak flatpak-builder -y
        
      - name: Add flathub repo
        run: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build flatpak bundle
        run: |
          mkdir build
          sudo flatpak-builder --install-deps-from=flathub build org.polymc.PolyMC.yml
          flatpak build-export export build
          flatpak build-bundle export "org.polymc.PolyMC.flatpak" org.polymc.PolyMC --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          
      - name: Push-release
        uses: phuonghuynh/action-ghrelease@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: org.polymc.PolyMC.flatpak
